package provenance

import (
	"fmt"
	"path/filepath"
	"time"
)

// Tracker wraps a provenance Log with convenience methods for recording
// inferences, user decisions, generated artifacts, and tool runs.
type Tracker struct {
	Log Log
}

// NewTracker creates a new empty Tracker.
func NewTracker() *Tracker {
	return &Tracker{}
}

// RecordInference records a profiler-inferred finding.
func (t *Tracker) RecordInference(id, source, finding, confidence string) {
	t.Log.Append(Record{
		ID:        id,
		Type:      "inferred",
		Source:    source,
		Rationale: fmt.Sprintf("%s (confidence: %s)", finding, confidence),
		Timestamp: time.Now(),
	})
}

// RecordUserDecision records a decision made by the user during the interview.
func (t *Tracker) RecordUserDecision(id, value, rationale string) {
	t.Log.Append(Record{
		ID:        id,
		Type:      "user_stated",
		Source:    "interview",
		Rationale: fmt.Sprintf("chose %q: %s", value, rationale),
		Timestamp: time.Now(),
	})
}

// RecordGeneration records a generated artifact.
func (t *Tracker) RecordGeneration(id, artifact, generator string) {
	t.Log.Append(Record{
		ID:        id,
		Type:      "generated",
		Source:    generator,
		Artifact:  artifact,
		Rationale: fmt.Sprintf("generated by %s", generator),
		Timestamp: time.Now(),
	})
}

// RecordToolRun records the result of running an external tool.
func (t *Tracker) RecordToolRun(toolName, result string) {
	t.Log.Append(Record{
		ID:        fmt.Sprintf("tool-%s-%d", toolName, len(t.Log.Records)),
		Type:      "inferred",
		Source:    toolName,
		Rationale: result,
		Timestamp: time.Now(),
	})
}

// Save writes the tracker's log to the provenance directory as two JSON files:
// decisions.json (user_stated records) and inferred-evidence.json (all others).
func (t *Tracker) Save(dir string) error {
	decisions := &Log{}
	evidence := &Log{}

	for _, r := range t.Log.Records {
		if r.Type == "user_stated" {
			decisions.Records = append(decisions.Records, r)
		} else {
			evidence.Records = append(evidence.Records, r)
		}
	}

	if err := Save(decisions, filepath.Join(dir, "decisions.json")); err != nil {
		return fmt.Errorf("saving decisions: %w", err)
	}
	if err := Save(evidence, filepath.Join(dir, "inferred-evidence.json")); err != nil {
		return fmt.Errorf("saving evidence: %w", err)
	}
	return nil
}
