package builder

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/mkh/rice-railing/internal/constitution"
)

// RenderGitHubActionsWorkflow generates a CI workflow from the constitution.
func RenderGitHubActionsWorkflow(c *constitution.Constitution) (string, error) {
	tmpl, err := template.New("ci").Parse(githubActionsTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing CI template: %w", err)
	}

	data := ciTemplateData{
		HasGo:         containsLang(c.Project.Languages, "go"),
		HasTypeScript: containsLang(c.Project.Languages, "typescript") || containsLang(c.Project.Languages, "javascript"),
		HasPython:     containsLang(c.Project.Languages, "python"),
		HasRust:       containsLang(c.Project.Languages, "rust"),
		BlockOn:       c.Quality.BlockOn,
		HasLint:       containsCheck(c.Quality.BlockOn, "lint"),
		HasTests:      containsCheck(c.Quality.BlockOn, "tests"),
		HasTypecheck:  containsCheck(c.Quality.BlockOn, "typecheck"),
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("rendering CI template: %w", err)
	}

	return buf.String(), nil
}

type ciTemplateData struct {
	HasGo         bool
	HasTypeScript bool
	HasPython     bool
	HasRust       bool
	BlockOn       []string
	HasLint       bool
	HasTests      bool
	HasTypecheck  bool
}

func containsLang(langs []string, target string) bool {
	for _, l := range langs {
		if l == target {
			return true
		}
	}
	return false
}

func containsCheck(checks []string, target string) bool {
	for _, c := range checks {
		if c == target {
			return true
		}
	}
	return false
}

const githubActionsTemplate = `# Generated by rice-rail build-toolkit
# Do not edit manually — run 'rice-rail regenerate' to update
name: rice-rail checks

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{{- if .HasGo}}

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
{{- end}}
{{- if .HasTypeScript}}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
{{- end}}
{{- if .HasPython}}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e ".[dev]" || pip install -r requirements.txt || true
{{- end}}
{{- if .HasRust}}

      - uses: dtolnay/rust-toolchain@stable
{{- end}}
{{- if .HasLint}}

      # Lint
{{- if .HasGo}}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
{{- end}}
{{- if .HasTypeScript}}
      - name: lint
        run: npx eslint . || npx biome check .
{{- end}}
{{- if .HasPython}}
      - name: ruff
        run: ruff check .
{{- end}}
{{- if .HasRust}}
      - name: clippy
        run: cargo clippy -- -D warnings
{{- end}}
{{- end}}
{{- if .HasTypecheck}}

      # Type check
{{- if .HasTypeScript}}
      - name: tsc
        run: npx tsc --noEmit
{{- end}}
{{- if .HasPython}}
      - name: pyright
        run: pyright . || mypy .
{{- end}}
{{- end}}
{{- if .HasTests}}

      # Tests
{{- if .HasGo}}
      - name: test
        run: go test ./... -v
{{- end}}
{{- if .HasTypeScript}}
      - name: test
        run: npm test
{{- end}}
{{- if .HasPython}}
      - name: test
        run: pytest
{{- end}}
{{- if .HasRust}}
      - name: test
        run: cargo test
{{- end}}
{{- end}}
`
