package builder

import (
	"fmt"
	"strings"

	"github.com/mkh/rice-railing/internal/constitution"
	"github.com/mkh/rice-railing/internal/resolution"
)

// RenderOperatorGuide generates the operator-guide.md documentation.
func RenderOperatorGuide(c *constitution.Constitution) string {
	var b strings.Builder

	b.WriteString("# Operator Guide\n\n")
	b.WriteString("Generated by rice-rail. Do not edit manually — run `rice-rail regenerate` to update.\n\n")

	b.WriteString("## Quick Reference\n\n")
	b.WriteString("| Command | Purpose |\n")
	b.WriteString("|---------|--------|\n")
	b.WriteString("| `rice-rail check` | Run all blocking checks |\n")
	b.WriteString("| `rice-rail fix` | Run safe autofixes |\n")
	b.WriteString("| `rice-rail baseline` | Normalize codebase to policy |\n")
	b.WriteString("| `rice-rail cycle \"<intent>\"` | Daily work loop |\n")
	b.WriteString("| `rice-rail report` | Show toolkit status |\n")
	b.WriteString("| `rice-rail explain <id>` | Explain any rule or artifact |\n")
	b.WriteString("| `rice-rail doctor` | Diagnose toolkit health |\n\n")

	b.WriteString("## Safety Policy\n\n")
	b.WriteString(fmt.Sprintf("- **Safety mode**: %s\n", c.Quality.SafetyMode))
	b.WriteString(fmt.Sprintf("- **Safe autofix**: %v\n", c.Automation.AllowSafeAutofix))
	b.WriteString(fmt.Sprintf("- **Unsafe autofix**: %v (requires --with-ai flag)\n", c.Automation.AllowUnsafeAutofix))
	b.WriteString(fmt.Sprintf("- **Generated codemods**: %v\n", c.Automation.AllowGeneratedCodemods))
	b.WriteString(fmt.Sprintf("- **Cross-module rewrites**: %v\n\n", c.Automation.AllowCrossModuleRewrites))

	b.WriteString("## Blocking Checks\n\n")
	b.WriteString("These checks must pass for any change to be accepted:\n\n")
	for _, check := range c.Quality.BlockOn {
		b.WriteString(fmt.Sprintf("- %s\n", check))
	}

	b.WriteString("\n## Advisory Checks\n\n")
	b.WriteString("These produce warnings but do not block:\n\n")
	for _, check := range c.Quality.AdvisoryOn {
		b.WriteString(fmt.Sprintf("- %s\n", check))
	}

	b.WriteString("\n## Scope Limits\n\n")
	b.WriteString(fmt.Sprintf("- Max files per cycle: %d\n", c.Quality.MaxChangedFilesPerCycle))
	b.WriteString(fmt.Sprintf("- Max lines per cycle: %d\n", c.Quality.MaxChangedLinesPerCycle))

	if c.Architecture.TargetStyle != "" {
		b.WriteString(fmt.Sprintf("\n## Architecture\n\n"))
		b.WriteString(fmt.Sprintf("- Target style: %s\n", c.Architecture.TargetStyle))
		if c.Architecture.Layering.Enabled {
			b.WriteString(fmt.Sprintf("- Layers: %v\n", c.Architecture.Layering.Layers))
			b.WriteString("- Forbidden dependencies:\n")
			for _, fd := range c.Architecture.Layering.ForbiddenDependencies {
				b.WriteString(fmt.Sprintf("  - %s → %s\n", fd.From, fd.To))
			}
		}
	}

	b.WriteString("\n## Workflow\n\n")
	b.WriteString(fmt.Sprintf("- Separate baseline from features: %v\n", c.Workflow.SeparateBaselineAndFeatureWork))
	b.WriteString(fmt.Sprintf("- Constitution changes need ack: %v\n", c.Workflow.RequireHumanAckForConstitutionChanges))
	b.WriteString(fmt.Sprintf("- CI integration: %v\n", c.Workflow.GenerateCIIntegration))

	return b.String()
}

// RenderRuleCatalog generates the rule-catalog.md documentation.
func RenderRuleCatalog(c *constitution.Constitution, plan *resolution.RolloutPlan) string {
	var b strings.Builder

	b.WriteString("# Rule Catalog\n\n")
	b.WriteString("Generated by rice-rail. Do not edit manually — run `rice-rail regenerate` to update.\n\n")

	b.WriteString("## Blocking Rules\n\n")
	b.WriteString("| Check | Severity | Status |\n")
	b.WriteString("|-------|----------|--------|\n")
	for _, check := range c.Quality.BlockOn {
		b.WriteString(fmt.Sprintf("| %s | BLOCKING | Active |\n", check))
	}

	b.WriteString("\n## Advisory Rules\n\n")
	b.WriteString("| Check | Severity | Status |\n")
	b.WriteString("|-------|----------|--------|\n")
	for _, check := range c.Quality.AdvisoryOn {
		b.WriteString(fmt.Sprintf("| %s | WARNING | Active |\n", check))
	}

	if c.Architecture.Layering.Enabled {
		b.WriteString("\n## Architecture Rules\n\n")
		b.WriteString("| Rule | Type |\n")
		b.WriteString("|------|------|\n")
		if c.Architecture.DependencyPolicy.NoCycles {
			b.WriteString("| No import cycles | BLOCKING |\n")
		}
		if c.Architecture.DependencyPolicy.RestrictCrossContextImports {
			b.WriteString("| Restrict cross-context imports | BLOCKING |\n")
		}
		for _, fd := range c.Architecture.Layering.ForbiddenDependencies {
			b.WriteString(fmt.Sprintf("| No %s → %s | BLOCKING |\n", fd.From, fd.To))
		}
	}

	if c.Architecture.DomainRules.NoFrameworkTypesInDomain {
		b.WriteString("\n## Domain Rules\n\n")
		b.WriteString("| Rule | Status |\n")
		b.WriteString("|------|--------|\n")
		b.WriteString("| No framework types in domain | Active |\n")
		if c.Architecture.DomainRules.RepositoriesAsInterfacesOnly {
			b.WriteString("| Repositories as interfaces only | Active |\n")
		}
		if c.Architecture.DomainRules.AdaptersAtEdgesOnly {
			b.WriteString("| Adapters at edges only | Active |\n")
		}
	}

	if plan != nil && len(plan.Steps) > 0 {
		b.WriteString("\n## Pending Rollout\n\n")
		b.WriteString("| # | Capability | Action | Risk |\n")
		b.WriteString("|---|-----------|--------|------|\n")
		for _, step := range plan.Steps {
			b.WriteString(fmt.Sprintf("| %d | %s | %s | %s |\n", step.Order, step.Capability, step.Action, step.Risk))
		}
	}

	return b.String()
}
