package builder

const wrapperCheck = `#!/usr/bin/env bash
# Generated by rice-rail build-toolkit. Do not edit manually.
set -euo pipefail
exec rice-rail check "$@"
`

const wrapperFix = `#!/usr/bin/env bash
# Generated by rice-rail build-toolkit. Do not edit manually.
set -euo pipefail
exec rice-rail fix "$@"
`

const wrapperBaseline = `#!/usr/bin/env bash
# Generated by rice-rail build-toolkit. Do not edit manually.
set -euo pipefail
exec rice-rail baseline "$@"
`

const wrapperCycle = `#!/usr/bin/env bash
# Generated by rice-rail build-toolkit. Do not edit manually.
set -euo pipefail
exec rice-rail cycle "$@"
`

const wrapperReport = `#!/usr/bin/env bash
# Generated by rice-rail build-toolkit. Do not edit manually.
set -euo pipefail
exec rice-rail report "$@"
`

const wrapperExplain = `#!/usr/bin/env bash
# Generated by rice-rail build-toolkit. Do not edit manually.
set -euo pipefail
exec rice-rail explain "$@"
`
